#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

# data directory for config.json
DATA_DIR="${TRIM_DATA_SHARE_PATHS%%:*}"

# write the command to start your program here
CMD="${TRIM_APPDEST}/server/email-notify -port 8543"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

start_process() {
    if status; then
        return 0
    fi

    log_msg "Starting process ..."
    
    # change to server directory for static files
    cd ${TRIM_APPDEST}/server
    
    # run the process
    bash -c "${CMD}" >> ${LOG_FILE} 2>&1 &
    
    # write pid to pidfile
    printf "%s" "$!" > ${PID_FILE}
    
    return 0
}

stop_process() {
    log_msg "Stopping process ..."

    if [ -r "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        log_msg "pid=${pid}"
        
        if ! check_process "${pid}"; then
            rm -f "${PID_FILE}"
            log_msg "Process not running, remove pid file"
            return 0
        fi

        log_msg "send TERM signal to PID:${pid}..."
        kill -TERM ${pid} >> ${LOG_FILE} 2>&1

        local count=0
        while check_process "${pid}" && [ $count -lt 10 ]; do
            sleep 1
            count=$((count + 1))
            log_msg "waiting process terminal... (${count}s/10s)"
        done

        if check_process "${pid}"; then
            log_msg "send KILL signal to PID:${pid}..."
            kill -KILL "${pid}" 2>/dev/null || true
            sleep 1
        fi
        
        rm -f "${PID_FILE}"
        log_msg "Process stopped, pid file removed."
    else
        log_msg "No pid file found, nothing to stop."
    fi

    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0  # process exist
    else
        return 1  # process not exist
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            rm -f "${PID_FILE}"
        fi    
    fi

    return 1
}

case $1 in
start)
    start_process
    ;;
stop)
    stop_process
    ;;
status)
    if status; then 
        exit 0
    else 
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
